const cp = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const { parseUnifiedDiff } = require('./diff.js');
const { loadFindingsFromSarif } = require('./findings.js');
const { DEFAULT_PROTECTED_PATHS } = require('./paths.js');
const { scoreRisk, shouldFail } = require('./risk.js');
const { readJsonFile } = require('./runner.js');
const { runSemgrepOnFiles, semgrepAvailable } = require('./scanner.js');

// The second line is the stable marker used to detect and safely uninstall
// a FixRelay-owned hook. Do NOT change this string without bumping the version.
const FIXRELAY_HOOK_MARKER = '# FixRelay pre-commit security gate';

/**
 * The hook script template. __FAIL_ON__ is replaced at install time.
 */
const HOOK_SCRIPT_TEMPLATE = `#!/bin/sh
# FixRelay pre-commit security gate
# Generated by \`fixrelay hook install\`. Remove with \`fixrelay hook uninstall\`
# or by deleting this file. Bypass once with \`git commit --no-verify\`.

set -e

if ! command -v fixrelay >/dev/null 2>&1; then
  echo "FixRelay: 'fixrelay' command not found on PATH; skipping pre-commit scan." >&2
  exit 0
fi

fixrelay hook check --fail-on __FAIL_ON__
`;

/**
 * Get the git hooks directory for the given repo, respecting core.hooksPath.
 * Falls back to .git/hooks if the git command fails.
 *
 * @param {string} repoPath
 * @param {function} _spawn
 * @returns {string}
 */
function getHooksDir(repoPath, _spawn = cp.spawnSync) {
  const result = _spawn('git', ['config', 'core.hooksPath'], {
    cwd: repoPath,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe']
  });
  if (result.status === 0 && result.stdout) {
    const custom = result.stdout.trim();
    return path.isAbsolute(custom) ? custom : path.resolve(repoPath, custom);
  }
  return path.join(repoPath, '.git', 'hooks');
}

/**
 * Install the FixRelay pre-commit hook into the given repo.
 *
 * @param {{ repoPath, failOn?, force?, _spawn?, _fs? }} opts
 * @returns {{ hookPath: string }}
 */
function writeHook({ repoPath, failOn = 'high', force = false, _spawn = cp.spawnSync, _fs = fs } = {}) {
  if (!repoPath) throw new Error('repoPath is required');

  const hooksDir = getHooksDir(repoPath, _spawn);

  // Ensure the hooks directory exists — git normally creates it, but some
  // shallow clones (e.g., CI environments) may not have it.
  _fs.mkdirSync(hooksDir, { recursive: true });

  const hookPath = path.join(hooksDir, 'pre-commit');

  // Safety check: refuse to overwrite a hook that isn't ours unless --force
  if (_fs.existsSync(hookPath)) {
    const existing = _fs.readFileSync(hookPath, 'utf8');
    if (!existing.includes(FIXRELAY_HOOK_MARKER) && !force) {
      throw new Error(
        `A pre-commit hook already exists at ${hookPath} and is not managed by FixRelay. ` +
        'Pass --force to overwrite it, or remove it manually first.'
      );
    }
  }

  const script = HOOK_SCRIPT_TEMPLATE.replace('__FAIL_ON__', failOn);
  _fs.writeFileSync(hookPath, script, { encoding: 'utf8', mode: 0o755 });

  return { hookPath };
}

/**
 * Remove the FixRelay pre-commit hook from the given repo.
 * Refuses to remove a hook that isn't ours.
 *
 * @param {{ repoPath, _spawn?, _fs? }} opts
 */
function removeHook({ repoPath, _spawn = cp.spawnSync, _fs = fs } = {}) {
  if (!repoPath) throw new Error('repoPath is required');

  const hooksDir = getHooksDir(repoPath, _spawn);
  const hookPath = path.join(hooksDir, 'pre-commit');

  if (!_fs.existsSync(hookPath)) {
    throw new Error(`No pre-commit hook found at ${hookPath}`);
  }

  const content = _fs.readFileSync(hookPath, 'utf8');
  if (!content.includes(FIXRELAY_HOOK_MARKER)) {
    throw new Error(
      `The pre-commit hook at ${hookPath} is not managed by FixRelay. ` +
      'Remove it manually to avoid accidental data loss.'
    );
  }

  _fs.unlinkSync(hookPath);
}

/**
 * Get the list of staged (added, copied, modified, renamed) file paths.
 * Deleted files are excluded because Semgrep cannot scan them.
 *
 * @param {{ cwd?, _spawn? }} opts
 * @returns {string[]}
 */
function getStagedFiles({ cwd = process.cwd(), _spawn = cp.spawnSync } = {}) {
  const result = _spawn('git', ['diff', '--cached', '--name-only', '--diff-filter=ACMR'], {
    cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe']
  });

  if (result.status !== 0) {
    return [];
  }

  return String(result.stdout || '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
}

/**
 * Get the unified diff of staged changes.
 *
 * @param {{ cwd?, _spawn? }} opts
 * @returns {string}
 */
function getStagedDiff({ cwd = process.cwd(), _spawn = cp.spawnSync } = {}) {
  const result = _spawn('git', ['diff', '--cached', '--unified=0'], {
    cwd,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe']
  });
  return result.status === 0 ? String(result.stdout || '') : '';
}

/**
 * Run the pre-commit security check against staged files.
 *
 * This is called by the hook script via `fixrelay hook check`.
 *
 * Exit code semantics (returned in result.exitCode):
 *   0 — clean or Semgrep unavailable (with warning)
 *   1 — gate triggered (findings meet fail-on threshold)
 *   2 — configuration error
 *
 * @param {{ cwd?, failOn?, semgrepConfig?, protectedPaths?, _spawn?, _readJsonFile? }} opts
 * @returns {{ exitCode: number, risk: object, blockingFindings: object[], message: string }}
 */
function runHookCheck({
  cwd = process.cwd(),
  failOn = 'high',
  semgrepConfig = 'auto',
  protectedPaths = DEFAULT_PROTECTED_PATHS,
  _spawn = cp.spawnSync,
  _readJsonFile = null
} = {}) {
  const readJson = _readJsonFile || readJsonFile;

  // If Semgrep is not installed, exit 0 with a warning (CI remains the source of truth)
  if (!semgrepAvailable(_spawn)) {
    return {
      exitCode: 0,
      risk: null,
      blockingFindings: [],
      message: "FixRelay: Semgrep is not installed; skipping pre-commit scan. Install Semgrep for local security checks."
    };
  }

  const stagedFiles = getStagedFiles({ cwd, _spawn });

  if (stagedFiles.length === 0) {
    return {
      exitCode: 0,
      risk: null,
      blockingFindings: [],
      message: 'FixRelay: No staged files to scan.'
    };
  }

  const scanResult = runSemgrepOnFiles({
    cwd,
    files: stagedFiles,
    config: semgrepConfig,
    _spawn
  });

  if (scanResult.skipped) {
    return {
      exitCode: 0,
      risk: null,
      blockingFindings: [],
      message: 'FixRelay: No files to scan.'
    };
  }

  if (!scanResult.ok) {
    // Semgrep configuration error — do not block the commit (fail open)
    return {
      exitCode: 0,
      risk: null,
      blockingFindings: [],
      message: `FixRelay: Semgrep scan failed (${scanResult.error}); skipping pre-commit check.`
    };
  }

  let findings = [];
  try {
    const sarifData = readJson(scanResult.sarifPath);
    findings = loadFindingsFromSarif(sarifData, scanResult.sarifPath);
  } catch (err) {
    return {
      exitCode: 0,
      risk: null,
      blockingFindings: [],
      message: `FixRelay: Could not read Semgrep output (${err.message}); skipping pre-commit check.`
    };
  }

  const stagedDiff = getStagedDiff({ cwd, _spawn });
  const diffContext = parseUnifiedDiff(stagedDiff);

  const risk = scoreRisk(findings, diffContext, { protectedPaths, scope: 'pr' });
  const blocked = shouldFail(risk.level, failOn);
  const blockingFindings = findings.filter((f) => f.severity === 'high' || f.severity === 'critical');

  let message;
  if (blocked) {
    const lines = [
      `FixRelay: Pre-commit blocked — ${risk.level} risk (${findings.length} finding${findings.length === 1 ? '' : 's'})`,
      ...blockingFindings.slice(0, 3).map((f) => `  ${f.severity.toUpperCase()} ${f.file || 'unknown'}${f.line ? `:${f.line}` : ''} — ${f.title}`)
    ];
    if (findings.length > 3) lines.push(`  ... and ${findings.length - 3} more`);
    lines.push('');
    lines.push('Run `fixrelay generate` for a full report and agent fix prompt.');
    lines.push('Bypass once with: git commit --no-verify');
    message = lines.join('\n');
  } else if (findings.length > 0) {
    message = `FixRelay: ${findings.length} finding${findings.length === 1 ? '' : 's'} (${risk.level} risk) — below ${failOn} threshold, proceeding.`;
  } else {
    message = `FixRelay: No findings in staged files.`;
  }

  return {
    exitCode: blocked ? 1 : 0,
    risk,
    blockingFindings,
    message
  };
}

module.exports = {
  FIXRELAY_HOOK_MARKER,
  HOOK_SCRIPT_TEMPLATE,
  getStagedDiff,
  getStagedFiles,
  getHooksDir,
  removeHook,
  runHookCheck,
  writeHook
};
